In [1]:
from sklearn import svm
from gameClasses import *
from sklearn.linear_model import LogisticRegression
# from plotConMatrix import plot_confusion_matrix
from sklearn.metrics import accuracy_score
import math as m
print("Importing Classes")

AI score: 0, Pl score: 0.
[[4 4 4 4 4 4]
 [4 4 4 4 4 4]]
Importing Classes


In [2]:
def movesRandom(state,player):
    board = [state,True]
    while not(state.isTerminal()) and board[1]:
        print(state,board[1])
        moves = state.legalMoves(player)
        move = random.choice(moves)
        board = state.result(move)
        
        if state.isTerminal() or len(moves) == 1:
            break
    # print(board[0].board)
    return board

# Data Generation

In [10]:
features = []
labels = []



for i in range(0,100):
    initial = [0,0,np.full((2,6), 4)]
    
    initial[2][1][random.randint(0,5)] += 1
    initial[2][0][random.randint(0,5)] -= 1
    initial[2][1][random.randint(0,5)] += 1
    initial[2][0][random.randint(0,5)] -= 1
    initial[2][1][random.randint(0,5)] += 1
    initial[2][0][random.randint(0,5)] -= 1
    
    print(initial[2])
    a = MancalaState(initial)
    
    aiDepth = random.randint(4,5)
    plDepth = random.randint(1,2)
    
    count = 0
    count1 = 0 
    while not(a.isTerminal()):
        count += 1
        a = minimax(a,aiDepth, 0)[0]

        if count > 4:
    #         print(0,a.board.flatten())
            count1 += 1
            features += [list(a.board.flatten())]
        if a.isTerminal():
            break
        #pl1
        a = minimax(a,plDepth, 1)[0]
        if count > 4:
    #         print(1,a.board.flatten())
            count1 += 1
            features += [list(a.board.flatten())]
    labels += [a.aiScore-a.plScore] * count1
    print(a.aiScore-a.plScore)
    del a


[[4 3 3 3 4 4]
 [4 4 5 5 5 4]]
38
[[3 4 4 4 3 3]
 [5 4 4 6 4 4]]
4
[[4 4 3 3 3 4]
 [4 4 5 5 4 5]]
34
[[3 3 4 4 3 4]
 [4 6 4 5 4 4]]
-26
[[4 4 2 3 4 4]
 [5 4 4 6 4 4]]
26
[[4 3 4 4 4 2]
 [5 4 4 6 4 4]]
-14
[[4 3 4 3 3 4]
 [5 6 4 4 4 4]]
32
[[4 2 4 4 3 4]
 [4 4 4 6 5 4]]
38
[[2 4 4 3 4 4]
 [5 5 4 5 4 4]]
-32
[[3 4 4 3 4 3]
 [6 4 4 4 4 5]]
-18
[[4 4 4 2 3 4]
 [5 4 4 5 5 4]]
-24
[[4 4 2 4 4 3]
 [4 4 4 5 5 5]]
34
[[3 4 3 4 4 3]
 [4 4 4 5 4 6]]


KeyboardInterrupt: 

In [78]:
features = np.array(features)
labels = np.array(labels)
# np.save("features", features)
# np.save("labels", labels)
print(features,labels)

[[4 1 2 ... 3 1 1]
 [4 1 2 ... 0 0 0]
 [4 2 3 ... 0 0 0]
 ...
 [0 0 1 ... 3 0 0]
 [0 0 1 ... 4 1 0]
 [0 0 0 ... 0 0 0]] [-16 -16 -16 ... -28 -28 -28]


In [5]:
features = np.load("features.npy")
labels = np.load("labels.npy")
def learnLogisticalReg(x_train, y_train):
    model = LogisticRegression(solver = 'lbfgs')
    model.fit(x_train, y_train)
    return model

In [6]:
def evaluate(X_test,y_test,model,title1):
    y_pred = model.predict(X_test)
    np.set_printoptions(precision=2)
    print(np.sum((y_test-y_pred)**2)/len(X_test))
    print(title1,"Accuracy", accuracy_score(y_test, y_pred))

In [7]:
size = len(features)
T_size = m.floor(size*.70)
model3 = learnLogisticalReg(features[0:T_size],labels[0:T_size])
T_size

/Users/mazeyarmoeini/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


922

In [8]:
evaluate(features[size-T_size:],labels[size-T_size:],model3,"Logistical Regression")

110.28633405639913
Logistical Regression Accuracy 0.3633405639913232


In [9]:
random.randint(1,3)

2

AttributeError: 'int' object has no attribute 'shape'